version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "Postgres2019!"
    ports:
      - "15432:5432"
    volumes:
      - /Users/willowrocha/Dev/Projetos/Exams/Paripassu/DB:/var/lib/postgresql/data