version: '3'
services:
    api:
        image: ticket-manager-api
        build:
            context: .
        container_name: api
        ports:
            - "8081:8080"
        depends_on:
            - db
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
            - SPRING_DATASOURCE_USERNAME=postgres
            - SPRING_DATASOURCE_PASSWORD=postgres
            - SPRING_JPA_HIBERNATE_DDL_AUTO=update
        networks: 
          - ticket-manager-network
          - ticket-manager-db-network
    db:
        image: postgres
        container_name: db
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "15432:5432"
        networks: 
          - ticket-manager-db-network
networks: 
  ticket-manager-network:
    external: true
    driver: bridge
  ticket-manager-db-network:
    driver: bridge